export default {
  // AnimatedVCaret
  'active'           :'active',
  'alt'              :'alt-',
  // SVG
  'anim'             :'anim',
  // Label
  'basic'            :'basic',
  'block'            :'block',
  'center'           :'ctr',
  'circle'           :'c',
  'compact'          :' compact',
  'content'          :'content',
  'contour'          :'contour',
  'disabled'         :'disabled',
  'error'            :'err',
  'headSection'      :'head section',
  'header'           :'header',
  'horizontalStretch':'h-stretch',
  'icon'             :'if',
  'iconInside'       :'i',
  'image'            :'img',
  // GrayscaleIcon
  'imgFit'           :'fit',
  'incard'           :'incard',
  'input'            :'input',
  'inputs'           :'fw sin',
  'inverted'         :'inv',
  'label'            :'label',
  'left'             :'lft',
  'lib'              :'fw',
  'light'            :'light',
  //Checklist
  'list'             :'list',
  'loading'          :'loading',
  'meta'             :'meta',
  'min'              :'min',
  'name'             :'name',
  'part'             :'part',
  'question'         :'ref',
  'relativeSize'     :'r-',
  'right'            :'rgt',
  'section'          :'section',
  'selectable'       :'select',
  'semi'             :'semi',
  'shadow'           :'sh-',
  'shadowActive'     :'sha',
  'shadowHover'      :'shh-',
  // Label
  'simple'           :'simple',
  'simpleHover'      :'simpleh',
  'size'             :'s-',
  'small'            :'small',
  'stroke'           :'stroke',
  'svg'              :'svg',
  'title'            :'title',
  'transparent'      :'alpha',
  // GrayscaleIcon, Label
  'transition'       :'t',
  'valid'            :'val',
  'vertical'         :'vrt',
  'verticalStretch'  :'v-stretch',
}
